name: Notify Main Repo

on:
  push:
    branches: [main]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger main repo workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.MAIN_REPO_TOKEN }}
          repository: <YOUR_USER>/Eventy
          event-type: submodule-updated
          client-payload: '{"submodule": "${{ github.repository }}"}'
